### ISSUE TITLE
.crx not working

### ISSUE THREAD

**Issue by retallicka** [myth/Adressaway#3]
I found and tried to use this today on
Mac OSX 10.11.6
Chrome Version 53.0.2785.143

I could not load the extension into Chrome

**Comment by myth** [comment]
Enable the developer mode checkbox at the top. Should work.

**Comment by myth** [comment]
@retallicka are you still having issues or has this been resolved? I can't seem to reproduce.

**Comment by retallicka** [comment]
Yes it's working. Not sure why it didn't work before. Upgraded to Chrome 54, maybe that helped. Thanks!
