### ISSUE TITLE
The plugin seems to be broken

### ISSUE THREAD

**Issue by larvel** [myth/Adressaway#4]
The plugin no longer works. 

Articles on Adressa Plus are no longer avaliable without paying. 

Could you see if you can make changes accordingly?

Thanks a million for the add-on!

**Comment by myth** [comment]
It looks like they finally fixed their paywall, and in that case, the trick that made this add-on work will not work any more. I will take another look when I get home from work. They have known about this add-on for a few years now, so it's about time they finally did something.

**Comment by myth** [comment]
Sorry, but it looks like they've shut the door for the approach used by this extension. Perhaps someone else will stumble across another way around it in the future.

**Comment by larvel** [comment]
Thanks for trying! :)
